### ISSUE TITLE
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select * from Users u where u.EMAIL_VERIFICATION_STATUS = 'true' limit ? offset ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement

### ISSUE THREAD

**Issue by seanmayer** [seanmayer/java-restful-refresher#2]
```
org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select * from Users u where u.EMAIL_VERIFICATION_STATUS = 'true' limit ? offset ?]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
 at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException([HibernateJpaDialect.java:259](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java%3A259)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible([HibernateJpaDialect.java:233](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java%3A233)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible([AbstractEntityManagerFactoryBean.java:551](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java%3A551)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible([ChainedPersistenceExceptionTranslator.java:61](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java%3A61)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.dao.support.DataAccessUtils.translateIfNecessary([DataAccessUtils.java:242](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java%3A242)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke([PersistenceExceptionTranslationInterceptor.java:152](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java%3A152)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:186](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A186)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke([CrudMethodMetadataPostProcessor.java:145](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor%24CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java%3A145)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:186](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A186)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke([ExposeInvocationInterceptor.java:97](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java%3A97)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:186](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A186)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke([JdkDynamicAopProxy.java:215](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java%3A215)%22%2C%22mobile-app-ws%22%5D))
 at jdk.proxy2/jdk.proxy2.$Proxy123.findAllUsersWithConfirmedEmailAddress(Unknown Source)
 at com.appsdeveloperblog.app.ws.io.repositories.UserRepositoryTest.testGetVerifiedUsers([UserRepositoryTest.java:38](command:_java.test.openStackTrace?%5B%22%5Ctat%20com.appsdeveloperblog.app.ws.io.repositories.UserRepositoryTest.testGetVerifiedUsers(UserRepositoryTest.java%3A38)%22%2C%22mobile-app-ws%22%5D))
 at java.base/java.util.ArrayList.forEach([ArrayList.java:1511](command:_java.test.openStackTrace?%5B%22%5Ctat%20java.base%2Fjava.util.ArrayList.forEach(ArrayList.java%3A1511)%22%2C%22mobile-app-ws%22%5D))
 at java.base/java.util.ArrayList.forEach([ArrayList.java:1511](command:_java.test.openStackTrace?%5B%22%5Ctat%20java.base%2Fjava.util.ArrayList.forEach(ArrayList.java%3A1511)%22%2C%22mobile-app-ws%22%5D))

Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
 at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert([SQLExceptionTypeDelegate.java:63](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java%3A63)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert([StandardSQLExceptionConverter.java:37](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java%3A37)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert([SqlExceptionHelper.java:113](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java%3A113)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement([StatementPreparerImpl.java:186](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.engine.jdbc.internal.StatementPreparerImpl%24StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java%3A186)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement([StatementPreparerImpl.java:151](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java%3A151)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.prepareQueryStatement([Loader.java:2122](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.prepareQueryStatement(Loader.java%3A2122)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.executeQueryStatement([Loader.java:2059](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.executeQueryStatement(Loader.java%3A2059)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.executeQueryStatement([Loader.java:2037](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.executeQueryStatement(Loader.java%3A2037)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.doQuery([Loader.java:956](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.doQuery(Loader.java%3A956)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections([Loader.java:357](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java%3A357)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.doList([Loader.java:2868](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.doList(Loader.java%3A2868)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.doList([Loader.java:2850](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.doList(Loader.java%3A2850)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.listIgnoreQueryCache([Loader.java:2682](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java%3A2682)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.Loader.list([Loader.java:2677](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.Loader.list(Loader.java%3A2677)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.loader.custom.CustomLoader.list([CustomLoader.java:338](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java%3A338)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.internal.SessionImpl.listCustomQuery([SessionImpl.java:2186](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java%3A2186)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.internal.AbstractSharedSessionContract.list([AbstractSharedSessionContract.java:1204](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java%3A1204)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.query.internal.NativeQueryImpl.doList([NativeQueryImpl.java:177](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java%3A177)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.query.internal.AbstractProducedQuery.list([AbstractProducedQuery.java:1617](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java%3A1617)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.query.Query.getResultList([Query.java:165](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.query.Query.getResultList(Query.java%3A165)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke([SharedEntityManagerCreator.java:406](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.orm.jpa.SharedEntityManagerCreator%24DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java%3A406)%22%2C%22mobile-app-ws%22%5D))
 at jdk.proxy2/jdk.proxy2.$Proxy155.getResultList(Unknown Source)
 at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute([JpaQueryExecution.java:179](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.query.JpaQueryExecution%24PagedExecution.doExecute(JpaQueryExecution.java%3A179)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute([JpaQueryExecution.java:90](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java%3A90)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute([AbstractJpaQuery.java:156](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java%3A156)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute([AbstractJpaQuery.java:144](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java%3A144)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke([RepositoryMethodInvoker.java:137](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java%3A137)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke([RepositoryMethodInvoker.java:121](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java%3A121)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke([QueryExecutorMethodInterceptor.java:159](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java%3A159)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke([QueryExecutorMethodInterceptor.java:138](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java%3A138)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:186](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A186)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation([TransactionInterceptor.java:123](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.transaction.interceptor.TransactionInterceptor%241.proceedWithInvocation(TransactionInterceptor.java%3A123)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction([TransactionAspectSupport.java:388](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java%3A388)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke([TransactionInterceptor.java:119](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java%3A119)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed([ReflectiveMethodInvocation.java:186](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java%3A186)%22%2C%22mobile-app-ws%22%5D))
 at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke([PersistenceExceptionTranslationInterceptor.java:137](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java%3A137)%22%2C%22mobile-app-ws%22%5D))
 ... 75 more
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Values of types "BOOLEAN" and "CHARACTER VARYING(4)" are not comparable; SQL statement:
select * from Users u where u.EMAIL_VERIFICATION_STATUS = 'true' limit ? offset ? [90110-212]
 at org.h2.message.DbException.getJdbcSQLException([DbException.java:632](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.message.DbException.getJdbcSQLException(DbException.java%3A632)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.message.DbException.getJdbcSQLException([DbException.java:477](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.message.DbException.getJdbcSQLException(DbException.java%3A477)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.message.DbException.get([DbException.java:223](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.message.DbException.get(DbException.java%3A223)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.value.TypeInfo.checkComparable([TypeInfo.java:764](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.value.TypeInfo.checkComparable(TypeInfo.java%3A764)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.expression.condition.Comparison.optimize([Comparison.java:159](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.expression.condition.Comparison.optimize(Comparison.java%3A159)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.expression.Expression.optimizeCondition([Expression.java:148](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.expression.Expression.optimizeCondition(Expression.java%3A148)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.command.query.Select.prepareExpressions([Select.java:1177](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.command.query.Select.prepareExpressions(Select.java%3A1177)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.command.query.Query.prepare([Query.java:218](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.command.query.Query.prepare(Query.java%3A218)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.command.Parser.prepareCommand([Parser.java:574](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.command.Parser.prepareCommand(Parser.java%3A574)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.engine.SessionLocal.prepareLocal([SessionLocal.java:631](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java%3A631)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.engine.SessionLocal.prepareCommand([SessionLocal.java:554](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java%3A554)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.jdbc.JdbcConnection.prepareCommand([JdbcConnection.java:1116](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java%3A1116)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.jdbc.JdbcPreparedStatement.([JdbcPreparedStatement.java:92](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.jdbc.JdbcPreparedStatement.%3Cinit%3E(JdbcPreparedStatement.java%3A92)%22%2C%22mobile-app-ws%22%5D))
 at org.h2.jdbc.JdbcConnection.prepareStatement([JdbcConnection.java:288](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java%3A288)%22%2C%22mobile-app-ws%22%5D))
 at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement([ProxyConnection.java:337](command:_java.test.openStackTrace?%5B%22%5Ctat%20com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java%3A337)%22%2C%22mobile-app-ws%22%5D))
 at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
 at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare([StatementPreparerImpl.java:149](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.engine.jdbc.internal.StatementPreparerImpl%245.doPrepare(StatementPreparerImpl.java%3A149)%22%2C%22mobile-app-ws%22%5D))
 at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement([StatementPreparerImpl.java:176](command:_java.test.openStackTrace?%5B%22%5Ctat%20org.hibernate.engine.jdbc.internal.StatementPreparerImpl%24StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java%3A176)%22%2C%22mobile-app-ws%22%5D))
 ... 109 more
```

**Comment by seanmayer** [comment]
https://github.com/seanmayer/java-restful-refresher/commit/51839299a7d85ae403a2a1294633a5ad7c083058
